INSERT INTO users (name) VALUES
('Alice'),
('Bruno'),
('Carlos'),
('Daniela'),
('Eduardo'),
('Fernanda'),
('Gabriel'),
('Helena'),
('Igor'),
('Juliana'),
('Kaio'),
('Larissa'),
('Marcos'),
('Natália'),
('Otávio');

INSERT INTO orders (user_id, total) VALUES
(1, 150.00),
(2, 230.50),
(3, 99.99),
(4, 320.00),
(5, 75.00),
(6, 410.90),
(7, 180.00),
(8, 250.00),
(9, 60.00),
(10, 500.00),
(11, 135.75),
(12, 220.00),
(13, 310.40),
(14, 90.00),
(15, 275.30);

INSERT INTO payments (order_id, status) VALUES
(1, 'paid'),
(2, 'paid'),
(3, 'pending'),
(4, 'cancelled'),
(5, 'paid'),
(6, 'paid'),
(7, 'pending'),
(8, 'paid'),
(9, 'cancelled'),
(10, 'paid'),
(11, 'pending'),
(12, 'paid'),
(13, 'paid'),
(14, 'cancelled'),
(15, 'paid');


INSERT INTO products (name) VALUES
('Keyboard'),
('Mouse'),
('Monitor'),
('Notebook'),
('Headset'),
('Webcam'),
('Printer'),
('Desk'),
('Chair'),
('USB Cable'),
('HD External'),
('SSD'),
('Router'),
('Smartphone'),
('Tablet');

INSERT INTO order_items (order_id, product_id) VALUES
(1, 1),
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(4, 6),
(5, 7),
(6, 8),
(7, 9),
(8, 10),
(9, 11),
(10, 12),
(11, 13),
(12, 14),
(13, 15);


INSERT INTO departments (name) VALUES
('IT'),
('Human Resources'),
('Finance'),
('Marketing'),
('Sales'),
('Support'),
('Logistics'),
('Operations'),
('Legal'),
('Administration'),
('Security'),
('Engineering'),
('Design'),
('Product'),
('Management');

INSERT INTO employees (name, department_id) VALUES
('Alice', 1),
('Bruno', 2),
('Carlos', 3),
('Daniela', 4),
('Eduardo', 5),
('Fernanda', 6),
('Gabriel', 7),
('Helena', 8),
('Igor', 9),
('Juliana', 10),
('Kaio', 11),
('Larissa', 12),
('Marcos', 13),
('Natália', 14),
('Otávio', 15);

INSERT INTO professionals (name) VALUES
('Dr. João'),
('Dra. Maria'),
('Dr. Pedro'),
('Dra. Ana'),
('Dr. Lucas'),
('Dra. Paula'),
('Dr. Rafael'),
('Dra. Camila'),
('Dr. Bruno'),
('Dra. Luiza'),
('Dr. Diego'),
('Dra. Renata'),
('Dr. André'),
('Dra. Bianca'),
('Dr. Felipe');

INSERT INTO appointments (professional_id, status) VALUES
(1, 'scheduled'),
(2, 'scheduled'),
(3, 'completed'),
(4, 'cancelled'),
(5, 'scheduled'),
(6, 'completed'),
(7, 'scheduled'),
(8, 'cancelled'),
(9, 'completed'),
(10, 'scheduled'),
(11, 'completed'),
(12, 'scheduled'),
(13, 'cancelled'),
(14, 'completed'),
(15, 'scheduled');

